
spring:
  data:
    mongodb:
      database: 'clearpay_coin'
      host: 127.0.0.1
      port: 27017
    rest:
      return-body-on-create: true
      return-body-on-update: true
server:
  port: 8080
