spring:
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration"
  data:
    mongodb:
      database: 'clearpay_coin'
      host: 127.0.0.1
      port: 27017
    rest:
      return-body-on-create: true
      return-body-on-update: true
